# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzVXo732JxI-UjXkmCb1KFCroGGcbuAU
"""

!pip install -q pymupdf gradio

import fitz  # PyMuPDF
import gradio as gr

# ---- PDF Handling ---- #
def extract_text_from_pdf(pdf_file):
    doc = fitz.open(pdf_file.name)
    text = ""
    for page in doc:
        text += page.get_text()
    return text

# ---- Chunk the text for easier handling ---- #
def chunk_text(text, chunk_size=500):
    return [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]

# ---- Simple Search ---- #
def search_in_chunks(query, chunks):
    results = []
    for i, chunk in enumerate(chunks):
        if query.lower() in chunk.lower():
            results.append(f"Chunk {i+1}:\n{chunk[:200]}...")
        if len(results) == 5:
            break
    return results if results else ["No matches found"]

# ---- Simple Answer (just shows a relevant chunk) ---- #
def get_answer(question, chunks):
    matches = search_in_chunks(question, chunks)
    if matches:
        return f"Best match:\n\n{matches[0]}"
    return "No answer found in the document."

# ---- App State ---- #
pdf_text = None
chunks = None

# ---- Gradio UI ---- #
def upload_pdf(file):
    global pdf_text, chunks
    pdf_text = extract_text_from_pdf(file)
    chunks = chunk_text(pdf_text)
    return "📄 PDF loaded successfully! You can now ask questions or search."

def answer_question(question):
    if not chunks:
        return "❗ Upload a PDF first"
    return get_answer(question, chunks)

def search_text(query):
    if not chunks:
        return "❗ Upload a PDF first"
    return search_in_chunks(query, chunks)

with gr.Blocks() as demo:
    gr.Markdown("## 📘 StudyMate — Simple PDF Q&A System (No Errors)")

    with gr.Tab("1️⃣ Upload PDF"):
        pdf_input = gr.File(label="Upload a PDF")
        upload_btn = gr.Button("Load PDF")
        status_box = gr.Textbox(label="Status")

    with gr.Tab("2️⃣ Ask a Question"):
        question = gr.Textbox(label="Enter your question")
        ask_btn = gr.Button("Get Answer")
        answer_box = gr.Textbox(label="Answer", lines=6)

    with gr.Tab("3️⃣ Search in PDF"):
        search_query = gr.Textbox(label="Search text")
        search_btn = gr.Button("Search")
        search_results = gr.Textbox(label="Results", lines=8)

    upload_btn.click(upload_pdf, pdf_input, status_box)
    ask_btn.click(answer_question, question, answer_box)
    search_btn.click(search_text, search_query, search_results)

demo.launch(share=True)